"use client";

import { ChangeEvent, DragEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Row = Record<string, string>;
type Stats = { rows: number; value: number; average: number; pricePerSqm: number; actualArea: number; areas: Group[]; propertyTypes: Group[]; procedures: Group[]; timeline: { name: string; value: number }[] };
type Group = { name: string; value: number; count: number };
type TrendPoint = { label: string; value: number; count?: number };
type ExecutiveData = { median: number; averageSize: number; averagePsf: number; monthly: TrendPoint[]; psfTrend: TrendPoint[]; buildings: Group[]; bedrooms: Group[]; propertyTypes: Group[]; histogram: TrendPoint[]; metros: Group[]; malls: Group[]; expensive: Row[]; heatAreas: string[]; heatRooms: string[]; heat: Record<string, number> };
type Message = { role: "user" | "assistant"; text: string };
const money = new Intl.NumberFormat("en-AE", { maximumFractionDigits: 0 });
const compact = new Intl.NumberFormat("en-AE", { notation: "compact", maximumFractionDigits: 1 });
const sqmToSqft = 10.7639;

function parseCsv(input: string): Row[] {
  const lines: string[][] = []; let row: string[] = [], field = "", quoted = false;
  for (let i = 0; i < input.length; i += 1) { const c = input[i], n = input[i + 1]; if (c === '"' && quoted && n === '"') { field += '"'; i += 1; } else if (c === '"') quoted = !quoted; else if (c === "," && !quoted) { row.push(field); field = ""; } else if ((c === "\n" || c === "\r") && !quoted) { if (c === "\r" && n === "\n") i += 1; row.push(field); if (row.some(Boolean)) lines.push(row); row = []; field = ""; } else field += c; }
  if (field || row.length) { row.push(field); lines.push(row); }
  const headers = (lines.shift() || []).map((h) => h.replace(/^\uFEFF/, "").trim());
  return lines.map((values) => Object.fromEntries(headers.map((h, i) => [h, values[i]?.trim() || ""])));
}
function analyze(rows: Row[]): Stats {
  const sum = (items: Row[], key: string) => items.reduce((total, item) => total + (Number(item[key]) || 0), 0);
  const groups = (key: string) => Object.entries(rows.reduce<Record<string, Row[]>>((acc, item) => { const name = item[key] || "Not specified"; (acc[name] ||= []).push(item); return acc; }, {})).map(([name, items]) => ({ name, count: items.length, value: sum(items, "TRANS_VALUE") })).sort((a, b) => b.value - a.value).slice(0, 6);
  const value = sum(rows, "TRANS_VALUE"), actualArea = sum(rows, "ACTUAL_AREA");
  const timeline = Object.entries(rows.reduce<Record<string, number>>((acc, item) => { const date = item.INSTANCE_DATE?.slice(0, 10); if (date) acc[date] = (acc[date] || 0) + (Number(item.TRANS_VALUE) || 0); return acc; }, {})).sort(([a], [b]) => a.localeCompare(b)).slice(-14).map(([name, total]) => ({ name: name.slice(5), value: total }));
  return { rows: rows.length, value, actualArea, average: value / rows.length, pricePerSqm: actualArea ? value / actualArea : 0, areas: groups("AREA_EN"), propertyTypes: groups("PROP_TYPE_EN"), procedures: groups("GROUP_EN"), timeline };
}
function executiveData(rows: Row[]): ExecutiveData {
  const number = (row: Row, key: string) => Number(row[key]) || 0;
  const value = (row: Row) => number(row, "TRANS_VALUE");
  const psf = (row: Row) => { const sqft = number(row, "ACTUAL_AREA") * sqmToSqft; return sqft ? value(row) / sqft : 0; };
  const grouped = (key: string, limit = 10) => Object.entries(rows.reduce<Record<string, Row[]>>((all, row) => { const name = row[key] || "Not specified"; (all[name] ||= []).push(row); return all; }, {})).map(([name, items]) => ({ name, count: items.length, value: items.reduce((sum, item) => sum + value(item), 0) })).sort((a, b) => b.count - a.count).slice(0, limit);
  const monthlyMap = rows.reduce<Record<string, Row[]>>((all, row) => { const month = row.INSTANCE_DATE?.slice(0, 7) || "Unknown"; (all[month] ||= []).push(row); return all; }, {});
  const monthly = Object.entries(monthlyMap).sort(([a], [b]) => a.localeCompare(b)).map(([label, items]) => ({ label, value: items.reduce((sum, item) => sum + value(item), 0), count: items.length }));
  const psfTrend = Object.entries(monthlyMap).sort(([a], [b]) => a.localeCompare(b)).map(([label, items]) => ({ label, value: items.reduce((sum, item) => sum + psf(item), 0) / items.length }));
  const prices = rows.map(value).filter(Boolean).sort((a, b) => a - b); const low = prices[0] || 0, high = prices.at(-1) || 0, width = Math.max((high - low) / 10, 1); const histogram = Array.from({ length: 10 }, (_, index) => { const start = low + width * index, end = index === 9 ? high + 1 : start + width; return { label: `${compact.format(start)}–${compact.format(end)}`, value: rows.filter((row) => value(row) >= start && value(row) < end).length }; });
  const areas = grouped("AREA_EN", 8).map((item) => item.name); const rooms = grouped("ROOMS_EN", 6).map((item) => item.name); const heat: Record<string, number> = {};
  areas.forEach((area) => rooms.forEach((room) => { const items = rows.filter((row) => row.AREA_EN === area && row.ROOMS_EN === room); heat[`${area}|${room}`] = items.length ? items.reduce((sum, item) => sum + psf(item), 0) / items.length : 0; }));
  return { median: prices.length ? prices[Math.floor(prices.length / 2)] : 0, averageSize: rows.length ? rows.reduce((sum, row) => sum + number(row, "ACTUAL_AREA"), 0) / rows.length : 0, averagePsf: rows.length ? rows.reduce((sum, row) => sum + psf(row), 0) / rows.length : 0, monthly, psfTrend, buildings: grouped("PROJECT_EN"), bedrooms: grouped("ROOMS_EN", 8), propertyTypes: grouped("PROP_TYPE_EN", 8), histogram, metros: grouped("NEAREST_METRO_EN"), malls: grouped("NEAREST_MALL_EN"), expensive: [...rows].sort((a, b) => value(b) - value(a)).slice(0, 10), heatAreas: areas, heatRooms: rooms, heat };
}

export default function Home() {
  const [rows, setRows] = useState<Row[]>([]); const [fileName, setFileName] = useState("Dubai Land Transactions · Jan–Jul 2026");
  const [columnFilters, setColumnFilters] = useState<Record<string, string>>({}); const [chartType, setChartType] = useState<"bars" | "columns" | "donut">("bars");
  const [unit, setUnit] = useState<"m2" | "sqft">("m2"); const [areaMin, setAreaMin] = useState(""); const [areaMax, setAreaMax] = useState(""); const [dateStart, setDateStart] = useState(""); const [dateEnd, setDateEnd] = useState(""); const [dragging, setDragging] = useState(false); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { Promise.all(["/dubai-land-transactions-2026-part-1.csv", "/dubai-land-transactions-2026-part-2.csv"].map((path) => fetch(path).then((r) => r.text()))).then(([first, second]) => setRows([...parseCsv(first), ...parseCsv(second)])).catch(() => setFileName("Dataset unavailable — upload a CSV")); }, []);
  const load = async (file?: File) => { if (!file) return; setRows(parseCsv(await file.text())); setFileName(file.name); reset(); };
  const headers = useMemo(() => Object.keys(rows[0] || {}), [rows]);
  const valuesByHeader = useMemo(() => Object.fromEntries(headers.map((header) => [header, [...new Set(rows.map((r) => r[header]).filter(Boolean))].sort()])), [rows, headers]) as Record<string, string[]>;
  useEffect(() => { if (headers.length) setColumnFilters((existing) => Object.fromEntries(headers.map((header) => [header, existing[header] || ""]))); }, [headers]);
  const areaFactor = unit === "sqft" ? sqmToSqft : 1;
  const filtered = useMemo(() => rows.filter((r) => {
    const area = Number(r.ACTUAL_AREA) * areaFactor;
    const date = r.INSTANCE_DATE?.slice(0, 10);
    return Object.entries(columnFilters).every(([key, value]) => !value || r[key] === value) && (!areaMin || area >= Number(areaMin)) && (!areaMax || area <= Number(areaMax)) && (!dateStart || date >= dateStart) && (!dateEnd || date <= dateEnd);
  }), [rows, columnFilters, areaMin, areaMax, areaFactor, dateStart, dateEnd]);
  const stats = useMemo(() => filtered.length ? analyze(filtered) : null, [filtered]); const executive = useMemo(() => filtered.length ? executiveData(filtered) : null, [filtered]); const maxBar = Math.max(...(stats?.areas.map((x) => x.value) || [1])); const maxTimeline = Math.max(...(stats?.timeline.map((x) => x.value) || [1]));
  const reset = () => { setColumnFilters(Object.fromEntries(headers.map((header) => [header, ""]))); setAreaMin(""); setAreaMax(""); setDateStart(""); setDateEnd(""); };
  const context = useMemo(() => stats ? ({ records: stats.rows, filters: { ...Object.fromEntries(Object.entries(columnFilters).filter(([, value]) => value)), area_range: areaMin || areaMax ? `${areaMin || "0"}–${areaMax || "∞"} ${unit === "sqft" ? "sq ft" : "m²"}` : "none" }, metrics: { total_value_aed: Math.round(stats.value), average_ticket_aed: Math.round(stats.average), actual_area_sqm: Math.round(stats.actualArea), price_per_sqm_aed: Math.round(stats.pricePerSqm), price_per_sqft_aed: Math.round(stats.pricePerSqm / sqmToSqft) }, top_areas: stats.areas, property_mix: stats.propertyTypes, transaction_groups: stats.procedures, recent_daily_value: stats.timeline, samples: filtered.slice(0, 20).map((r) => ({ date: r.INSTANCE_DATE, area: r.AREA_EN, property: r.PROP_TYPE_EN, subtype: r.PROP_SB_TYPE_EN, rooms: r.ROOMS_EN, value_aed: r.TRANS_VALUE, actual_area_sqm: r.ACTUAL_AREA, project: r.PROJECT_EN })) }) : null, [stats, columnFilters, areaMin, areaMax, unit, filtered]);
  const onDrop = (e: DragEvent<HTMLDivElement>) => { e.preventDefault(); setDragging(false); load(e.dataTransfer.files[0]); };

  return <main><section className="hero"><div className="brand"><span className="drjay-logo"><i>Dr</i>Jay</span><span className="brand-name">NEXUS <b>DUBAI</b><small>REAL ESTATE INTELLIGENCE</small></span></div><div className="hero-copy"><p className="eyebrow">Dubai land transactions · 2026</p><h1>The market,<br/><em>decoded.</em></h1><p>Decision-grade intelligence for Dubai’s property market, from raw transaction data to clear direction.</p></div><div className="live-signals"><span>LIVE MARKET SIGNALS&nbsp;&nbsp;•&nbsp;&nbsp; LIVE MARKET SIGNALS&nbsp;&nbsp;•&nbsp;&nbsp; LIVE MARKET SIGNALS&nbsp;&nbsp;•&nbsp;&nbsp;</span></div></section>
    <div className="dashboard-shell"><aside className="filter-rail">{stats && <FilterRail headers={headers} valuesByHeader={valuesByHeader} columnFilters={columnFilters} onChange={(header, value) => setColumnFilters({ ...columnFilters, [header]: value })} unit={unit} setUnit={setUnit} areaMin={areaMin} setAreaMin={setAreaMin} areaMax={areaMax} setAreaMax={setAreaMax} dateStart={dateStart} setDateStart={setDateStart} dateEnd={dateEnd} setDateEnd={setDateEnd} reset={reset}/>}</aside><section className="workspace"><div className="toolbar"><div><p className="eyebrow">Market workspace</p><h2>{rows.length ? "Transaction overview" : "Loading market data…"}</h2>{stats && <MarketSummary rows={filtered}/>}</div>{rows.length > 0 && <button className="replace" onClick={() => input.current?.click()}>Replace CSV</button>}</div><input ref={input} className="file-input" type="file" accept=".csv,text/csv" onChange={(e: ChangeEvent<HTMLInputElement>) => load(e.target.files?.[0])}/>
      {!stats ? <div className={`dropzone ${dragging ? "is-dragging" : ""}`} onDragOver={(e) => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={onDrop} onClick={() => input.current?.click()}><div className="upload-icon">↑</div><h3>Loading the transaction dataset</h3><p>Or click here to choose a replacement CSV.</p></div> : <>
        <div className="data-note"><span className="status-dot"/> {fileName} <b>{money.format(stats.rows)} matching records</b></div>{executive && <ExecutiveDashboard stats={stats} data={executive} rows={filtered}/>}<DataChat context={context}/>
      </>}</section></div><footer>© 2026 DrJay <span>·</span> PRIVATE ANALYSIS · DATA PROCESSED IN YOUR BROWSER</footer></main>;
}
function Select({ label, value, onChange, first, options }: { label: string; value: string; onChange: (value: string) => void; first: string; options: string[] }) { return <label>{label.replace(/_EN$/, "").replaceAll("_", " ")}<select value={value} onChange={(e) => onChange(e.target.value)}><option>{first}</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function MarketSummary({ rows }: { rows: Row[] }) { const text = useMemo(() => { const dates = [...new Set(rows.map((row) => row.INSTANCE_DATE?.slice(0, 10)).filter(Boolean))].sort(); const period = (days: number) => { const current = dates.slice(-days), previous = dates.slice(-days * 2, -days); const currentRows = rows.filter((row) => current.includes(row.INSTANCE_DATE?.slice(0, 10))); const previousRows = rows.filter((row) => previous.includes(row.INSTANCE_DATE?.slice(0, 10))); const movement = currentRows.length >= previousRows.length ? "up" : "down"; const change = previousRows.length ? Math.round(Math.abs(currentRows.length - previousRows.length) / previousRows.length * 100) : 0; return { current, rows: currentRows, movement, change }; }; const fortnight = period(14), month = period(30); const areas = Object.entries(fortnight.rows.reduce<Record<string, number>>((all, row) => { const area = row.AREA_EN || "Not specified"; all[area] = (all[area] || 0) + 1; return all; }, {})).sort(([, a], [, b]) => b - a); const [area, count] = areas[0] || ["Not specified", 0]; return { fortnight, month, area, count }; }, [rows]); const change = (item: { movement: string; change: number }) => <b className={item.movement}>{item.movement === "up" ? "▲" : "▼"} {item.movement} {item.change}%</b>; return <div className="market-summary"><p><span>Latest 2 weeks</span> · {money.format(text.fortnight.rows.length)} transactions, {change(text.fortnight)} versus the prior two weeks. <strong>{text.area}</strong> leads with {money.format(text.count)} transactions.</p><p><span>Latest month</span> · {money.format(text.month.rows.length)} transactions, {change(text.month)} versus the prior month.</p></div>; }
function FilterRail({ headers, valuesByHeader, columnFilters, onChange, unit, setUnit, areaMin, setAreaMin, areaMax, setAreaMax, dateStart, setDateStart, dateEnd, setDateEnd, reset }: { headers: string[]; valuesByHeader: Record<string, string[]>; columnFilters: Record<string, string>; onChange: (header: string, value: string) => void; unit: "m2" | "sqft"; setUnit: (unit: "m2" | "sqft") => void; areaMin: string; setAreaMin: (value: string) => void; areaMax: string; setAreaMax: (value: string) => void; dateStart: string; setDateStart: (value: string) => void; dateEnd: string; setDateEnd: (value: string) => void; reset: () => void }) { const groups = [["Transaction", ["TRANSACTION_NUMBER", "GROUP_EN", "PROCEDURE_EN"]], ["Property", ["IS_OFFPLAN_EN", "IS_FREE_HOLD_EN", "USAGE_EN", "AREA_EN", "PROP_TYPE_EN", "PROP_SB_TYPE_EN", "PROCEDURE_AREA", "ACTUAL_AREA", "ROOMS_EN", "PARKING"]], ["Location", ["NEAREST_METRO_EN", "NEAREST_MALL_EN", "NEAREST_LANDMARK_EN"]], ["Parties & project", ["TOTAL_BUYER", "TOTAL_SELLER", "MASTER_PROJECT_EN", "PROJECT_EN"]]] as const; return <div className="rail-inner"><div className="rail-head"><div><p className="eyebrow">Data controls</p><h3>Filter the view</h3><p>All source fields are available below.</p></div><button className="reset" onClick={reset}>Clear</button></div><section className="unit-filters rail-units"><div className="date-range"><span>Transaction date range</span><div className="date-inputs"><label>Start date<input type="date" value={dateStart} onChange={(e) => setDateStart(e.target.value)} aria-label="Starting transaction date"/></label><label>End date<input type="date" value={dateEnd} onChange={(e) => setDateEnd(e.target.value)} aria-label="Ending transaction date"/></label></div></div><label>Area & cost unit<select value={unit} onChange={(e) => setUnit(e.target.value as "m2" | "sqft")}><option value="m2">Square metres (m²)</option><option value="sqft">Square feet (sq ft)</option></select></label><div className="range-inputs"><label>Minimum area<input type="number" value={areaMin} onChange={(e) => setAreaMin(e.target.value)} placeholder="Min"/></label><label>Maximum area<input type="number" value={areaMax} onChange={(e) => setAreaMax(e.target.value)} placeholder="Max"/></label></div></section>{groups.map(([name, fields], index) => { const available = fields.filter((field) => headers.includes(field)); return available.length ? <details className="filter-group" key={name} open={index < 2}><summary>{name}<span>{available.filter((field) => columnFilters[field]).length || "All"}</span></summary><div>{available.map((header) => <Select key={header} label={header} value={columnFilters[header] || ""} onChange={(value) => onChange(header, value)} first="All values" options={valuesByHeader[header] || []}/>)}</div></details> : null; })}</div>; }
function AreaChart({ data, type, max }: { data: Group[]; type: "bars" | "columns" | "donut"; max: number }) { const colors = ["#275849", "#d0a653", "#63897d", "#b56c50", "#466d82", "#947b9a"]; const total = data.reduce((sum, item) => sum + item.value, 0); if (type === "donut") { let position = 0; const segments = data.map((item, index) => { const next = position + item.value / total * 100; const segment = `${colors[index]} ${position}% ${next}%`; position = next; return segment; }).join(", "); return <div className="donut-wrap"><div className="donut" style={{ background: `conic-gradient(${segments})` }}><span>AED<br/><b>{compact.format(total)}</b></span></div><div className="donut-legend">{data.map((item, index) => <div key={item.name}><i style={{ background: colors[index] }}/><span>{item.name}</span><b>{Math.round(item.value / total * 100)}%</b></div>)}</div></div>; } if (type === "columns") return <div className="area-columns">{data.map((item, index) => <div className="area-column" key={item.name}><i style={{ height: `${Math.max(8, item.value / max * 100)}%`, background: colors[index] }}/><span>{item.name}</span><b>{compact.format(item.value)}</b></div>)}</div>; return <div className="bar-list">{data.map((item, index) => <div className="bar-row" key={item.name}><div className="bar-label"><b>{String(index + 1).padStart(2, "0")}</b><span>{item.name}</span><strong>{compact.format(item.value)}</strong></div><div className="bar-track"><i style={{ width: `${item.value / max * 100}%`, background: colors[index] }}/></div></div>)}</div>; }
function ExecutiveDashboard({ stats, data, rows }: { stats: Stats; data: ExecutiveData; rows: Row[] }) { return <><div className="exec-kpis"><Metric label="Total transactions" value={money.format(stats.rows)} detail="Filtered transaction records"/><Metric label="Total sales value" value={`AED ${compact.format(stats.value)}`} detail="Aggregate transaction value"/><Metric label="Average sale price" value={`AED ${compact.format(stats.average)}`} detail="Value per transaction"/><Metric label="Median sale price" value={`AED ${compact.format(data.median)}`} detail="Middle transaction value"/><Metric label="Average property size" value={`${money.format(data.averageSize * sqmToSqft)} sq ft`} detail={`${money.format(data.averageSize)} m² average`}/><Metric label="Average AED / sq ft" value={`AED ${money.format(data.averagePsf)}`} detail={`AED ${money.format(data.averagePsf * sqmToSqft)} / m²`}/></div><div className="exec-grid"><ChartPanel title="Monthly sales trend" subtitle="Total sales value"><LineChart data={data.monthly} currency/></ChartPanel><ChartPanel title="Average price per sq.ft. over time" subtitle="Average AED / sq ft"><LineChart data={data.psfTrend}/></ChartPanel><ChartPanel title="Transactions by building" subtitle="Top 10 projects"><CountBars data={data.buildings}/></ChartPanel><ChartPanel title="Transactions by bedroom count" subtitle="Distribution by room type"><CountBars data={data.bedrooms}/></ChartPanel><ChartPanel title="Property type distribution" subtitle="Share of transactions"><DonutChart data={data.propertyTypes}/></ChartPanel><ChartPanel title="Price distribution" subtitle="Histogram of sale prices"><Histogram data={data.histogram}/></ChartPanel><ChartPanel title="Sales by nearest Metro" subtitle="Transactions by proximity"><CountBars data={data.metros}/></ChartPanel><ChartPanel title="Sales by nearest Mall" subtitle="Transactions by proximity"><CountBars data={data.malls}/></ChartPanel></div><section className="panel heat-panel"><div className="panel-head"><div><p className="eyebrow">Location × configuration</p><h3>Heat map of average AED / sq.ft.</h3></div></div><HeatMap data={data}/></section><TransactionTable title="Top 10 most expensive transactions" eyebrow="Premium inventory" rows={data.expensive}/><TransactionExplorer rows={rows}/></>; }
function TransactionTable({ title, eyebrow, rows }: { title: string; eyebrow: string; rows: Row[] }) { return <section className="panel transactions-table"><div className="panel-head"><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div></div><div className="table-responsive"><table><thead><tr><th>Date</th><th>Area</th><th>Building / Project</th><th>Type</th><th>Size</th><th>AED / sq ft</th><th>Sale value</th></tr></thead><tbody>{rows.map((row, index) => { const sqft = (Number(row.ACTUAL_AREA) || 0) * sqmToSqft; const psf = sqft ? (Number(row.TRANS_VALUE) || 0) / sqft : 0; return <tr key={`${row.TRANSACTION_NUMBER}-${index}`}><td>{row.INSTANCE_DATE?.slice(0, 10)}</td><td>{row.AREA_EN}</td><td>{row.PROJECT_EN || "—"}</td><td>{row.PROP_TYPE_EN}</td><td>{money.format(sqft)} sq ft</td><td>AED {money.format(psf)}</td><td><b>AED {money.format(Number(row.TRANS_VALUE) || 0)}</b></td></tr>; })}</tbody></table></div></section>; }
function TransactionExplorer({ rows }: { rows: Row[] }) { const [limit, setLimit] = useState(25); const latest = useMemo(() => [...rows].sort((a, b) => b.INSTANCE_DATE.localeCompare(a.INSTANCE_DATE)).slice(0, limit), [rows, limit]); return <section className="transaction-explorer"><div className="explorer-head"><div><p className="eyebrow">Transaction register</p><h3>Explore filtered transactions</h3></div><label>Show<select value={limit} onChange={(e) => setLimit(Number(e.target.value))}>{[25, 50, 100, 500].map((value) => <option key={value} value={value}>{value} transactions</option>)}</select></label></div><TransactionTable title={`Latest ${Math.min(limit, rows.length)} transactions`} eyebrow="Sorted by transaction date" rows={latest}/></section>; }
function ChartPanel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="panel exec-panel"><div className="panel-head"><div><p className="eyebrow">{subtitle}</p><h3>{title}</h3></div></div>{children}</section>; }
function LineChart({ data, currency = false }: { data: TrendPoint[]; currency?: boolean }) { const max = Math.max(...data.map((item) => item.value), 1); const width = 560, height = 190, pad = 28; const points = data.map((item, index) => `${pad + index * (width - pad * 2) / Math.max(data.length - 1, 1)},${height - pad - item.value / max * (height - pad * 2)}`).join(" "); const rising = (data.at(-1)?.value || 0) >= (data[0]?.value || 0); return <div className={`line-chart ${rising ? "is-rising" : "is-declining"}`}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={currency ? "Monthly sales value trend" : "Average price per square foot trend"}><path d={`M ${pad} ${height - pad} H ${width - pad}`} className="axis"/><polyline points={points} className="line"/>{data.map((item, index) => { const x = pad + index * (width - pad * 2) / Math.max(data.length - 1, 1), y = height - pad - item.value / max * (height - pad * 2); return <g key={item.label}><circle cx={x} cy={y} r="4"/><text x={x} y={height - 8}>{item.label.slice(5)}</text><title>{item.label}: {currency ? `AED ${money.format(item.value)}` : `AED ${money.format(item.value)} / sq ft`}</title></g>; })}</svg><b>{rising ? "▲ Increase" : "▼ Decline"} · {currency ? `AED ${compact.format(max)}` : `AED ${money.format(max)} / sq ft`}</b></div>; }
function CountBars({ data }: { data: Group[] }) { const max = Math.max(...data.map((item) => item.count), 1); return <div className="count-bars">{data.map((item) => <div key={item.name}><span>{item.name}</span><i><b style={{ width: `${item.count / max * 100}%` }}/></i><em>{money.format(item.count)}</em></div>)}</div>; }
function DonutChart({ data }: { data: Group[] }) { const colors = ["#275849", "#d0a653", "#63897d", "#b56c50", "#466d82", "#947b9a", "#947b9a", "#7d8a48"]; const total = data.reduce((sum, item) => sum + item.count, 0); let start = 0; const gradient = data.map((item, index) => { const end = start + item.count / total * 100; const chunk = `${colors[index]} ${start}% ${end}%`; start = end; return chunk; }).join(", "); return <div className="donut-wrap"><div className="donut" style={{ background: `conic-gradient(${gradient})` }}><span>Deals<br/><b>{money.format(total)}</b></span></div><div className="donut-legend">{data.map((item, index) => <div key={item.name}><i style={{ background: colors[index] }}/><span>{item.name}</span><b>{Math.round(item.count / total * 100)}%</b></div>)}</div></div>; }
function Histogram({ data }: { data: TrendPoint[] }) { const max = Math.max(...data.map((item) => item.value), 1); return <div className="histogram">{data.map((item) => <div key={item.label}><b style={{ height: `${Math.max(5, item.value / max * 100)}%` }}/><span>{item.label}</span><em>{money.format(item.value)}</em></div>)}</div>; }
function HeatMap({ data }: { data: ExecutiveData }) { const max = Math.max(...Object.values(data.heat), 1); const colors = ["#1677ff", "#19b7e8", "#1daf76", "#f6c344", "#ff8a3d", "#f05b47", "#8d5ae8"]; return <div className="heatmap"><div></div>{data.heatRooms.map((room) => <b key={room}>{room}</b>)}{data.heatAreas.flatMap((area) => [<strong key={`${area}-label`}>{area}</strong>, ...data.heatRooms.map((room) => { const value = data.heat[`${area}|${room}`]; const color = value ? colors[Math.min(colors.length - 1, Math.floor(value / max * colors.length))] : "#e4e9f1"; return <span key={`${area}|${room}`} style={{ backgroundColor: color, color: value ? "#fff" : "#61738d", opacity: value ? 0.95 : 1 }} title={`${area}, ${room}: AED ${money.format(value)} / sq ft`}>{value ? money.format(value) : "—"}</span>; })])}</div>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><span>{detail}</span></article>; }
function Breakdown({ title, eyebrow, data }: { title: string; eyebrow: string; data: Group[] }) { const total = data.reduce((sum, item) => sum + item.value, 0); return <article className="panel breakdown"><div className="panel-head"><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div></div>{data.map((item) => <div className="break-row" key={item.name}><span>{item.name}</span><b>{total ? Math.round(item.value / total * 100) : 0}%</b><small>{money.format(item.count)} deals</small></div>)}</article>; }
function DataChat({ context }: { context: object | null }) { const [messages, setMessages] = useState<Message[]>([{ role: "assistant", text: "Ask me anything about the transactions currently shown — for example, “Which area has the highest average ticket?”" }]); const [question, setQuestion] = useState(""); const [busy, setBusy] = useState(false); const ask = async (event: FormEvent) => { event.preventDefault(); const prompt = question.trim(); if (!prompt || busy) return; setQuestion(""); setMessages((items) => [...items, { role: "user", text: prompt }]); setBusy(true); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: prompt, context, history: messages.slice(-4) }) }); const data = await response.json(); setMessages((items) => [...items, { role: "assistant", text: data.answer || data.error || "I couldn’t answer that question." }]); } catch { setMessages((items) => [...items, { role: "assistant", text: "The assistant is unavailable right now." }]); } finally { setBusy(false); } }; return <section className="chat"><div className="chat-title"><div><p className="eyebrow">Data copilot</p><h3>Ask the transaction data</h3></div><span className="gemini-badge">Gemini · free tier</span></div><div className="messages">{messages.map((message, i) => <div key={i} className={`message ${message.role}`}>{message.text}</div>)}{busy && <div className="message assistant">Thinking…</div>}</div><form onSubmit={ask}><input value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="Ask about prices, areas, projects, or buyer activity…"/><button disabled={busy}>Ask</button></form><small>Answers are returned in text and reflect the current dashboard filters.</small></section>; }
